# Generated by Django 5.1.2 on 2024-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='reaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
