# Generated by Django 5.1.2 on 2024-11-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0003_answer_dislike_count_answer_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like_dislike_diff',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_dislike_diff',
        ),
    ]
