# Generated by Django 5.1.2 on 2024-12-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0005_remove_answer_reaction_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AskMe.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AskMe.profile'),
        ),
    ]
