# Generated by Django 4.2.17 on 2024-12-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0006_alter_answer_profile_alter_question_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
